services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=practice3'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=practice3'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_DATABASE: practice3
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
